#!/usr/bin/env bash
#comment
while IFS= read -r line
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/$SHELL. $USER_ID place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
	#echo "$line"
done < "/etc/passwd"
