#!/usr/bin/env bash
#comment
c=1
while [$c -lt 20]
do
	echo $c
	if [[$c -eq 4]]
	then
		echo bad lucj from China
	elif [[$c -eq 9]]
	then
		echo bad luck from Japan
	elif [[$c -eq 17]]
	then
		echo bad luck from Italy	
	fi
	c=$(($c+1))	
	
done
