#!/usr/bin/env bash
#comment
c=1
while [$c -lt 20]
do
	echo $c
	
	case $c in
		4)
			echo bad luck from China
		;;
		9)
			echo bad luick from Japan
		;;
		17)
			echo bad luck from Italy
		;;
	esac
	


	c=$(($c+1))	
	
done
