#!/usr/bin/env bash
#comment
s="school"
if [[ -f "$s" ]]
then
	echo school file exists
	if [[ find -s -name "$s" ]]
	then
		echo file is not empty
	else
		echo school file is not empty
	fi
	
	echo school is a regular file

else
	echo school file does not exist
fi
