#!/usr/bin/env bash
#
echo $$ > /var/run/myscript.pid
trap -o 'rm /var/run/myscript.pid; exit 1' SIGTERM SIGQUIT
trap 'echo I hate the kill command' 15
trap 'echo Y U no love me?!' 2
while true;
do
	echo To infinity and beyond
	sleep 2
done
