#!/usr/bin/env bash
#
echo $$ > /var/run/myscript.pid

trap 'echo I hate the kill command' 15
trap 'echo Y U no love me?!' 2
while true;
do
	echo To infinity and beyond
	sleep 2
done
trap "rm /var/run/myscript.pid || exit 1" 3 -o 15
